name: Build & Release

permissions:
  contents: write
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: mac
            arch: x64
          - os: windows-latest
            target: win
            arch: x64
          - os: ubuntu-latest
            target: linux
            arch: x64
    runs-on: ${{ matrix.os }}

    steps:
      # 1. Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0

      # 3. Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # 4. Build Electron app for the specific OS and architecture
      - name: Build Electron app
        run: yarn dist -- --${{ matrix.target }} --${{ matrix.arch }}

      # 5. Create GitHub release and upload artifacts
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          name: "req.io-${{ matrix.target }}-${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
